language: python
cache: pip
python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"
jobs:
  include:
    - python: 3.7
      os: linux
    - python: 3.8
      os: linux
install:
    - make init
    - pip install coveralls
    - pip install scrutinizer-ocular
script:
    - make test
    - make docs
after_script:
    - coveralls
    - ocular
