language: python
sudo: false
python:
    - "2.7"
#     - "3.3"
#     - "3.4"
#     - "3.5"
install:
    - make init
    - pip install coveralls
    - pip install scrutinizer-ocular
script:
    - make test
after_script:
    - coveralls
    - ocular
