language: python
os: linux
jobs:
  include:
    - python: 2.7
    - python: 3.4
    - python: 3.5
    - python: 3.6
    - python: 3.7
    - python: 3.8
      os: linux
install:
    - pip install -r requirements.txt
    - pip install coveralls
    - pip install scrutinizer-ocular
script:
    - make test
    - make docs
after_script:
    - coveralls
    - ocular
