language: python
os: linux
jobs:
  include:
# docs build
    - name: Docs (py36)
      python: 3.6
      install: make init
      script: make docs
      after_script: []
# linux
    - python: 2.7
    - python: 3.4
    - python: 3.5
    - python: 3.6
    - python: 3.7
    - python: 3.8
# OSX
    - name: OSX Python 2.7
      os: osx
      language: shell
      before_install:
        - cp -fv `which python2` `which python` || true
        - cp -fv `which pip2` `which pip` || true
        - pip install --upgrade pip
      after_script: []
    - name: OSX Python 3.7
      os: osx
      language: shell
      before_install:
        - cp -fv `which python3` `which python` || true
        - cp -fv `which pip3` `which pip` || true
        - pip install --upgrade pip
      after_script: []
# Windows
    - name: Win Python 3.6
      language: shell
      os: windows
      env: PATH=/c/Python36:/c/Python36/Scripts:$PATH
      before_install:
        - choco install python --version 3.6.8
        - python -m pip install --upgrade pip
      after_script: []
    - name: Win Python 3.7
      language: shell
      os: windows
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH
      before_install:
        - choco install python --version 3.7.4
        - python -m pip install --upgrade pip
      after_script: []
    - name: Win Python 3.8
      language: shell
      os: windows
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH
      before_install:
        - choco install python --version 3.8.2
        - python -m pip install --upgrade pip
      after_script: []
install:
    - pip install -r requirements.txt
    - pip install coveralls
    - pip install scrutinizer-ocular
script:
    - PYTHONHASHSEED=0 pytest --cov=steam tests
after_script:
    - coveralls
    - ocular
